### ISSUE TITLE
REACTION TIME TESTER GAME

### ISSUE THREAD

**Issue by 1-ARIjitS** [1-ARIjitS/Earth-Facts#3]
make a reaction time testing game using HTML, CSS, and javascript 
1. it is for an example js project.
2. it must test the reaction time of the user using simple js interaction

**Comment by Raksha25** [comment]
Hi @1-ARIjitS , I believe I can handle this issue pretty well.

**Comment by Aliex-dev** [comment]
i would love to work on it

**Comment by 1-ARIjitS** [comment]
i have merged the project do see.
